subnetID: some-new-subnet-id
allowedSSHSecurityGroupIDs:
  - id12
  - id5
  - id3
projectID: somethingnewer
SomeThingNew: shouldNotBeAdded
adminIdentityARNs:
  - something
  - somethingelse
somethingElse:
  somethingElse:value
kmsKeyARN: test6
databaseEncryption:
    kmsKeyARN: test3
